<?php

return [
  [
    'fullname' => 'John Doe',
    'password' => 'Admin@123',
    'contact_num' => '09171234567',
    'username' => 'johndoe',
    'role' => 'admin',
    'date_of_birth' => '1985-02-14',
    'gender' => 'Male',
    'nationality' => 'Filipino',
    'email' => 'john.doe@example.com',
    'emergency_contact' => 'Jane Doe - 09181231234',
    'passport_number' => 'P1234567',
    'passport_expiry' => '2030-05-31',
    'passport_issuing_country' => 'Philippines',
    'flight_id' => null,
    'passport_image' => [
      'filename' => 'johndoe.jpg',
      'filepath' => '/assets/img/johndoe.jpg',
      'mimetype' => 'image/jpeg',
      'size_bytes' => file_exists(IMAGES_PATH . '/johndoe.jpg') ? filesize(IMAGES_PATH . '/johndoe.jpg') : 0,

    ],
  ],
  [
    'fullname' => 'Alice Reyes',
    'password' => 'Alice@1234',
    'contact_num' => '09223334444',
    'username' => 'alice',
    'role' => 'client',
    'date_of_birth' => '1992-09-10',
    'gender' => 'Female',
    'nationality' => 'Filipino',
    'email' => 'alice.reyes@example.com',
    'emergency_contact' => 'Carlos Reyes - 09191110000',
    'passport_number' => 'P7654321',
    'passport_expiry' => '2029-11-20',
    'passport_issuing_country' => 'Philippines',
    'flight_id' => null,
    'passport_image' => [
      'filename' => 'alice.jpg',
      'filepath' => '/assets/img/alice.jpg',
      'mimetype' => 'image/jpeg',
      'size_bytes' => file_exists(IMAGES_PATH . '/alice.jpg') ? filesize(IMAGES_PATH . '/alice.jpg') : 0,

    ],
  ],
  [
    'fullname' => 'Mark Fernandez',
    'password' => 'Markie@456',
    'contact_num' => '09334445555',
    'username' => 'mark',
    'role' => 'client',
    'date_of_birth' => '1990-06-25',
    'gender' => 'Male',
    'nationality' => 'Filipino',
    'email' => 'mark.fernandez@example.com',
    'emergency_contact' => 'Lara Fernandez - 09224446666',
    'passport_number' => 'P9998888',
    'passport_expiry' => '2031-08-15',
    'passport_issuing_country' => 'Philippines',
    'flight_id' => null,
    'passport_image' => [
      'filename' => 'mark.jpg',
      'filepath' => '/assets/img/mark.jpg',
      'mimetype' => 'image/jpeg',
      'size_bytes' => file_exists(IMAGES_PATH . '/mark.jpg') ? filesize(IMAGES_PATH . '/mark.jpg') : 0,

    ],
  ],
];
