<?php
declare(strict_types=1);

// 1) Composer autoload
require 'vendor/autoload.php';

// 2) Bootstrap app
require 'bootstrap.php';

// 3) envSetter
require_once UTILS_PATH . '/envSetter.util.php';

// Load dummy data
$users = require_once DUMMIES_PATH . '/users.staticData.php';
$planets = require_once DUMMIES_PATH . '/planets.staticData.php';
$flights = require_once DUMMIES_PATH . '/flights.staticData.php';
$booking = require_once DUMMIES_PATH . '/booking.staticData.php';
$tickets = require_once DUMMIES_PATH . '/tickets.staticData.php';

// ——— Connect to PostgreSQL ———
$dsn = "pgsql:host={$pgConfig['host']};port={$pgConfig['port']};dbname={$pgConfig['db']}";
$pdo = new PDO($dsn, $pgConfig['user'], $pgConfig['pass'], [
  PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
]);

echo "✅ Connected to PostgreSQL via PDO\n";

// ——— Seeding Users ———
echo "🌱 Seeding users…\n";

// Prepare the insert statement (UUID is auto-generated by DEFAULT in DB)
$stmt = $pdo->prepare("
  INSERT INTO public.\"users\" (
    fullname,
    password,
    contact_num,
    username,
    role,
    passport_img
  ) VALUES (
    :fullname,
    :password,
    :contact_num,
    :username,
    :role,
    :passport_img
  )
");


foreach ($users as $u) {
  $stmt->bindValue(':fullname', $u['fullname']);
  $stmt->bindValue(':password', password_hash($u['password'], PASSWORD_DEFAULT));
  $stmt->bindValue(':contact_num', $u['contact_num']);
  $stmt->bindValue(':username', $u['username']);
  $stmt->bindValue(':role', $u['role']);
  $stmt->bindValue(':passport_img', $u['passport_img'], PDO::PARAM_LOB);
  $stmt->execute();
}



$planetStmt = $pdo->prepare("
  INSERT INTO public.\"planets\" (
    name,
    distance_from_earth,
    planet_img
  ) VALUES (
    :name,
    :distance_from_earth,
    :planet_img
  )
");

foreach ($planets as $p) {
  $planetStmt->bindValue(':name', $p['name']);
  $planetStmt->bindValue(':distance_from_earth', $p['distance_from_earth']);
  $planetStmt->bindValue(':planet_img', $p['planet_img'], PDO::PARAM_LOB);
  $planetStmt->execute();
}


$flightStmt = $pdo->prepare("
  INSERT INTO public.\"flights\" (
    departure_time,
    return_time,
    capacity,
    price,
    package_type
  ) VALUES (
    :departure_time,
    :return_time,
    :capacity,
    :price,
    :package_type
  ) RETURNING id
");

foreach ($flights as $f) {
  $flightStmt->execute([
    ':departure_time' => $f['departure_time'],
    ':return_time' => $f['return_time'],
    ':capacity' => $f['capacity'],
    ':price' => $f['price'],
    ':package_type' => $f['package_type'],
  ]);
  $flightId = $flightStmt->fetchColumn();
}

$bookingStmt = $pdo->prepare("
  INSERT INTO public.\"bookings\" (
    travel_date,
    seat_number,
    ticket_code,
    status,
    feedback
  ) VALUES (
    :travel_date,
    :seat_number,
    :ticket_code,
    :status,
    :feedback
  ) RETURNING id
");

foreach ($booking as $b) {
  $bookingStmt->execute([
    ':travel_date' => $b['travel_date'],
    ':seat_number' => $b['seat_number'],
    ':ticket_code' => $b['ticket_code'],
    ':status' => $b['status'],
    ':feedback' => $b['feedback'],
  ]);
  $bookingId = $bookingStmt->fetchColumn();
}

$ticketStmt = $pdo->prepare("
  INSERT INTO public.\"tickets\" (
    flight_number,
    launch_pad,
    gate,
    qr_code
  ) VALUES (
    :flight_number,
    :launch_pad,
    :gate,
    :qr_code
  )
");

foreach ($tickets as $t) {
  $ticketStmt->execute([
    ':flight_number' => $t['flight_number'],
    ':launch_pad' => $t['launch_pad'],
    ':gate' => $t['gate'],
    ':qr_code' => $t['qr_code'],
  ]);
}

echo "✅ PostgreSQL seeding complete!\n";
