<?php
declare(strict_types=1);

// 1) Composer autoload
require 'vendor/autoload.php';

// 2) Bootstrap app
require 'bootstrap.php';

// 3) envSetter
require_once UTILS_PATH . '/envSetter.util.php';

// Load dummy data
$users = require_once DUMMIES_PATH . '/users.staticData.php';
$planets = require_once DUMMIES_PATH . '/planets.staticData.php';
$flights = require_once DUMMIES_PATH . '/flights.staticData.php';
$booking = require_once DUMMIES_PATH . '/booking.staticData.php';
$tickets = require_once DUMMIES_PATH . '/tickets.staticData.php';

// ——— Connect to PostgreSQL ———
$dsn = "pgsql:host={$pgConfig['host']};port={$pgConfig['port']};dbname={$pgConfig['db']}";
$pdo = new PDO($dsn, $pgConfig['user'], $pgConfig['pass'], [
  PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
]);

echo "✅ Connected to PostgreSQL via PDO\n";

// ——— Seeding Users ———
echo "🌱 Seeding users…\n";

// Prepare the insert statement (UUID is auto-generated by DEFAULT in DB)
// Step 1: Insert into users (without passport_img)
$userStmt = $pdo->prepare("
  INSERT INTO public.\"users\" (
    fullname,
    password,
    contact_num,
    username,
    role
  ) VALUES (
    :fullname,
    :password,
    :contact_num,
    :username,
    :role
  ) RETURNING id
");

// Step 2: Insert into images
$imageStmt = $pdo->prepare("
  INSERT INTO public.\"images\" (
    user_id,
    filename,
    filepath,
    mimetype,
    size_bytes,
  ) VALUES (
    :user_id,
    :filename,
    :filepath,
    :mimetype,
    :size_bytes,
  ) RETURNING id
");

// Step 3: Update user's passport_img_id
$updateUserPassportStmt = $pdo->prepare("
  UPDATE public.\"users\" SET passport_img_id = :image_id WHERE id = :user_id
");

foreach ($users as $u) {
  // 1. Create user
  $userStmt->execute([
    ':fullname' => $u['fullname'],
    ':password' => password_hash($u['password'], PASSWORD_DEFAULT),
    ':contact_num' => $u['contact_num'],
    ':username' => $u['username'],
    ':role' => $u['role']
  ]);

  $userId = $userStmt->fetchColumn();

  // 2. Create image entry (you can update values based on your staticData)
  $imageStmt->execute([
    ':user_id' => $userId,
    ':filename' => $u['passport_image']['filename'],
    ':filepath' => $u['passport_image']['filepath'],
    ':mimetype' => $u['passport_image']['mimetype'],
    ':size_bytes' => $u['passport_image']['size_bytes'],
  ]);

  $imageId = $imageStmt->fetchColumn();

  // 3. Link image to user
  $updateUserPassportStmt->execute([
    ':image_id' => $imageId,
    ':user_id' => $userId
  ]);
}



$planetStmt = $pdo->prepare("
  INSERT INTO public.\"planets\" (
    name,
    distance_from_earth,
    planet_img
  ) VALUES (
    :name,
    :distance_from_earth,
    :planet_img
  )
");

foreach ($planets as $p) {
  $planetStmt->bindValue(':name', $p['name']);
  $planetStmt->bindValue(':distance_from_earth', $p['distance_from_earth']);
  $planetStmt->bindValue(':planet_img', $p['planet_img'], PDO::PARAM_LOB);
  $planetStmt->execute();
}


$flightStmt = $pdo->prepare("
  INSERT INTO public.\"flights\" (
    departure_time,
    return_time,
    capacity,
    price,
    package_type
  ) VALUES (
    :departure_time,
    :return_time,
    :capacity,
    :price,
    :package_type
  ) RETURNING id
");

foreach ($flights as $f) {
  $flightStmt->execute([
    ':departure_time' => $f['departure_time'],
    ':return_time' => $f['return_time'],
    ':capacity' => $f['capacity'],
    ':price' => $f['price'],
    ':package_type' => $f['package_type'],
  ]);
  $flightId = $flightStmt->fetchColumn();
}

$bookingStmt = $pdo->prepare("
  INSERT INTO public.\"bookings\" (
    travel_date,
    seat_number,
    ticket_code,
    status,
    feedback
  ) VALUES (
    :travel_date,
    :seat_number,
    :ticket_code,
    :status,
    :feedback
  ) RETURNING id
");

foreach ($booking as $b) {
  $bookingStmt->execute([
    ':travel_date' => $b['travel_date'],
    ':seat_number' => $b['seat_number'],
    ':ticket_code' => $b['ticket_code'],
    ':status' => $b['status'],
    ':feedback' => $b['feedback'],
  ]);
  $bookingId = $bookingStmt->fetchColumn();
}

$ticketStmt = $pdo->prepare("
  INSERT INTO public.\"tickets\" (
    flight_number,
    launch_pad,
    gate,
    qr_code
  ) VALUES (
    :flight_number,
    :launch_pad,
    :gate,
    :qr_code
  )
");

foreach ($tickets as $t) {
  $ticketStmt->execute([
    ':flight_number' => $t['flight_number'],
    ':launch_pad' => $t['launch_pad'],
    ':gate' => $t['gate'],
    ':qr_code' => $t['qr_code'],
  ]);
}

echo "✅ PostgreSQL seeding complete!\n";
