<?php
declare(strict_types=1);

// 1) Composer autoload
require 'vendor/autoload.php';

// 2) Bootstrap app
require 'bootstrap.php';

// 3) envSetter
require_once UTILS_PATH . '/envSetter.util.php';

// Load dummy data
$users = require_once DUMMIES_PATH . '/users.staticData.php';
$planets = require_once DUMMIES_PATH . '/planets.staticData.php';

// ——— Connect to PostgreSQL ———
$dsn = "pgsql:host={$pgConfig['host']};port={$pgConfig['port']};dbname={$pgConfig['db']}";
$pdo = new PDO($dsn, $pgConfig['user'], $pgConfig['pass'], [
  PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
]);

echo "✅ Connected to PostgreSQL via PDO\n";

// ——— Seeding Users ———
echo "🌱 Seeding users…\n";

// Prepare the insert statement (UUID is auto-generated by DEFAULT in DB)
$stmt = $pdo->prepare("
  INSERT INTO public.\"users\" (
    fullname,
    password,
    contact_num,
    username,
    role,
    passport_img,
    flight_id
  ) VALUES (
    :fullname,
    :password,
    :contact_num,
    :username,
    :role,
    :passport_img,
    :flight_id
  )
");


foreach ($users as $u) {
  $stmt->execute([
    ':fullname' => $u['fullname'],
    ':password' => password_hash($u['password'], PASSWORD_DEFAULT),
    ':contact_num' => $u['contact_num'],
    ':username' => $u['username'],
    ':role' => $u['role'],
    ':passport_img' => $u['passport_img'],
    ':flight_id' => $u['flight_id'],
  ]);
}

$planetStmt = $pdo->prepare("
  INSERT INTO public.\"planets\" (
    name,
    distance_from_earth,
    planet_img
  ) VALUES (
    :name,
    :distance_from_earth,
    :planet_img
  )
");

foreach ($planets as $p) {
  $planetStmt->execute([
    ':name' => $p['name'],
    ':distance_from_earth' => $p['distance_from_earth'],
    ':planet_img' => $p['planet_img'], 
  ]);
}

$flightStmt = $pdo->prepare("
  INSERT INTO public.\"flights\" (
    planet_id,
    departure_time,
    return_time,
    capacity,
    price,
    package_type
  ) VALUES (
    :planet_id,
    :departure_time,
    :return_time,
    :capacity,
    :price,
    :package_type
  ) RETURNING id
");

foreach ($flights as $f) {
  $flightStmt->execute([
    ':planet_id' => $f['planet_id'],
    ':departure_time' => $f['departure_time'],
    ':return_time' => $f['return_time'],
    ':capacity' => $f['capacity'],
    ':price' => $f['price'],
    ':package_type' => $f['package_type'],
  ]);
  $flightId = $flightStmt->fetchColumn();
}

$bookingStmt = $pdo->prepare("
  INSERT INTO public.\"bookings\" (
    user_id,
    flight_id,
    travel_date,
    seat_number,
    ticket_code,
    status,
    feedback
  ) VALUES (
    :user_id,
    :flight_id,
    :travel_date,
    :seat_number,
    :ticket_code,
    :status,
    :feedback
  ) RETURNING id
");

foreach ($bookings as $b) {
  $bookingStmt->execute([
    ':user_id' => $b['user_id'],
    ':flight_id' => $b['flight_id'],
    ':travel_date' => $b['travel_date'],
    ':seat_number' => $b['seat_number'],
    ':ticket_code' => $b['ticket_code'],
    ':status' => $b['status'],
    ':feedback' => $b['feedback'],
  ]);
  $bookingId = $bookingStmt->fetchColumn();
}

$ticketStmt = $pdo->prepare("
  INSERT INTO public.\"tickets\" (
    booking_id,
    flight_id,
    flight_number,
    launch_pad,
    gate,
    qr_code
  ) VALUES (
    :booking_id,
    :flight_id,
    :flight_number,
    :launch_pad,
    :gate,
    :qr_code
  )
");

foreach ($tickets as $t) {
  $ticketStmt->execute([
    ':booking_id' => $t['booking_id'],
    ':flight_id' => $t['flight_id'],
    ':flight_number' => $t['flight_number'],
    ':launch_pad' => $t['launch_pad'],
    ':gate' => $t['gate'],
    ':qr_code' => $t['qr_code'],
  ]);
}

echo "✅ PostgreSQL seeding complete!\n";
